// 国別のコールサインプレフィックス
export const countryPrefixes: Record<string, { prefix: string[]; country: string; region: string }> = {
  // 北米
  US: {
    prefix: [
      "K",
      "N",
      "W",
      "AA",
      "AB",
      "AC",
      "AD",
      "AE",
      "AF",
      "AG",
      "AI",
      "AJ",
      "AK",
      "KA",
      "KB",
      "KC",
      "KD",
      "KE",
      "KF",
      "KG",
      "KI",
      "KJ",
      "KK",
      "KL",
      "KM",
      "KN",
      "KO",
      "KP",
      "KQ",
      "KR",
      "KS",
      "KT",
      "KU",
      "KV",
      "KW",
      "KX",
      "KY",
      "KZ",
      "WA",
      "WB",
      "WC",
      "WD",
      "WE",
      "WF",
      "WG",
      "WH",
      "WI",
      "WJ",
      "WK",
      "WL",
      "WM",
      "WN",
      "WO",
      "WP",
      "WQ",
      "WR",
      "WS",
      "WT",
      "WU",
      "WV",
      "WW",
      "WX",
      "WY",
      "WZ",
    ],
    country: "United States",
    region: "North America",
  },
  CA: { prefix: ["VA", "VB", "VC", "VD", "VE", "VF", "VG", "VO", "VY"], country: "Canada", region: "North America" },
  MX: { prefix: ["XA", "XB", "XC", "XD", "XE", "XF", "XG", "XH", "XI"], country: "Mexico", region: "North America" },

  // 南米
  AR: { prefix: ["LO", "LP", "LQ", "LR", "LS", "LT", "LU", "LV", "LW"], country: "Argentina", region: "South America" },
  BR: {
    prefix: ["PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY", "ZV", "ZW", "ZX", "ZY", "ZZ"],
    country: "Brazil",
    region: "South America",
  },
  CL: { prefix: ["CA", "CB", "CC", "CD", "CE", "XQ", "XR"], country: "Chile", region: "South America" },

  // ヨーロッパ
  UK: { prefix: ["G", "M", "2E", "2I", "2M", "2W", "GX", "MX"], country: "United Kingdom", region: "Europe" },
  DE: {
    prefix: [
      "DA",
      "DB",
      "DC",
      "DD",
      "DE",
      "DF",
      "DG",
      "DH",
      "DI",
      "DJ",
      "DK",
      "DL",
      "DM",
      "DN",
      "DO",
      "DP",
      "DQ",
      "DR",
    ],
    country: "Germany",
    region: "Europe",
  },
  FR: { prefix: ["F", "TH", "TK", "TM", "TO", "TP", "TQ", "TV", "TW", "TX"], country: "France", region: "Europe" },
  IT: {
    prefix: ["I", "IK", "IN", "IQ", "IR", "IS", "IT", "IU", "IV", "IW", "IX", "IY", "IZ"],
    country: "Italy",
    region: "Europe",
  },
  ES: { prefix: ["EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH"], country: "Spain", region: "Europe" },
  RU: {
    prefix: [
      "R",
      "RA",
      "RB",
      "RC",
      "RD",
      "RE",
      "RF",
      "RG",
      "RH",
      "RI",
      "RJ",
      "RK",
      "RL",
      "RM",
      "RN",
      "RO",
      "RP",
      "RQ",
      "RR",
      "RS",
      "RT",
      "RU",
      "RV",
      "RW",
      "RX",
      "RY",
      "RZ",
      "UA",
      "UB",
      "UC",
      "UD",
      "UE",
      "UF",
      "UG",
      "UH",
      "UI",
      "UJ",
      "UK",
      "UL",
      "UM",
      "UN",
      "UO",
      "UP",
      "UQ",
      "UR",
      "US",
      "UT",
      "UU",
      "UV",
      "UW",
      "UX",
      "UY",
      "UZ",
    ],
    country: "Russia",
    region: "Europe",
  },

  // アジア
  JP: {
    prefix: [
      "JA",
      "JB",
      "JC",
      "JD",
      "JE",
      "JF",
      "JG",
      "JH",
      "JI",
      "JJ",
      "JK",
      "JL",
      "JM",
      "JN",
      "JO",
      "JP",
      "JQ",
      "JR",
      "JS",
      "7J",
      "7K",
      "7L",
      "7M",
      "7N",
      "8J",
      "8K",
      "8L",
      "8M",
      "8N",
    ],
    country: "Japan",
    region: "Asia",
  },
  CN: {
    prefix: [
      "BA",
      "BB",
      "BC",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BK",
      "BL",
      "BM",
      "BN",
      "BO",
      "BP",
      "BQ",
      "BR",
      "BS",
      "BT",
      "BU",
      "BV",
      "BW",
      "BX",
      "BY",
      "BZ",
      "XS",
    ],
    country: "China",
    region: "Asia",
  },
  KR: { prefix: ["DS", "DT", "D7", "D8", "D9", "HL"], country: "South Korea", region: "Asia" },
  IN: { prefix: ["AT", "AU", "AV", "AW", "VT", "VU", "VV", "VW"], country: "India", region: "Asia" },

  // オセアニア
  AU: { prefix: ["VH", "VI", "VJ", "VK", "VL", "VM", "VN", "VZ"], country: "Australia", region: "Oceania" },
  NZ: { prefix: ["ZL", "ZM"], country: "New Zealand", region: "Oceania" },

  // アフリカ
  ZA: { prefix: ["ZR", "ZS", "ZT", "ZU"], country: "South Africa", region: "Africa" },
  EG: { prefix: ["SU"], country: "Egypt", region: "Africa" },
}

// 名前のリスト
export const operatorNames = [
  "John",
  "David",
  "Michael",
  "Robert",
  "James",
  "William",
  "Richard",
  "Thomas",
  "Charles",
  "Joseph",
  "Mary",
  "Patricia",
  "Jennifer",
  "Linda",
  "Elizabeth",
  "Barbara",
  "Susan",
  "Jessica",
  "Sarah",
  "Karen",
  "Takashi",
  "Hiroshi",
  "Satoshi",
  "Kenji",
  "Akira",
  "Yuki",
  "Kazuki",
  "Daiki",
  "Ryo",
  "Shota",
  "Yoko",
  "Yumi",
  "Naomi",
  "Eri",
  "Mika",
  "Ayumi",
  "Haruka",
  "Nana",
  "Aoi",
  "Yui",
  "Hans",
  "Klaus",
  "Peter",
  "Franz",
  "Otto",
  "Heinrich",
  "Wolfgang",
  "Dieter",
  "Jürgen",
  "Manfred",
  "Anna",
  "Maria",
  "Ursula",
  "Helga",
  "Monika",
  "Ingrid",
  "Renate",
  "Sabine",
  "Claudia",
  "Andrea",
  "Pierre",
  "Jean",
  "Michel",
  "André",
  "Philippe",
  "Louis",
  "François",
  "Antoine",
  "Nicolas",
  "Daniel",
  "Marie",
  "Sophie",
  "Catherine",
  "Isabelle",
  "Anne",
  "Monique",
  "Françoise",
  "Martine",
  "Nicole",
  "Nathalie",
  "Carlos",
  "Juan",
  "Miguel",
  "Antonio",
  "José",
  "Manuel",
  "Francisco",
  "Javier",
  "Pedro",
  "Luis",
  "María",
  "Ana",
  "Carmen",
  "Isabel",
  "Dolores",
  "Pilar",
  "Teresa",
  "Rosa",
  "Cristina",
  "Laura",
]

// 都市のリスト
export const cities = [
  // 北米
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Toronto",
  "Montreal",
  "Vancouver",
  "Calgary",
  "Edmonton",
  "Ottawa",
  "Quebec City",
  "Winnipeg",
  "Hamilton",
  "Halifax",
  "Mexico City",
  "Guadalajara",
  "Monterrey",
  "Puebla",
  "Tijuana",
  "León",
  "Juárez",
  "Zapopan",
  "Mérida",
  "Cancún",

  // 南米
  "Buenos Aires",
  "Córdoba",
  "Rosario",
  "Mendoza",
  "La Plata",
  "San Miguel de Tucumán",
  "Mar del Plata",
  "Salta",
  "Santa Fe",
  "San Juan",
  "São Paulo",
  "Rio de Janeiro",
  "Brasília",
  "Salvador",
  "Fortaleza",
  "Belo Horizonte",
  "Manaus",
  "Curitiba",
  "Recife",
  "Porto Alegre",
  "Santiago",
  "Valparaíso",
  "Concepción",
  "La Serena",
  "Antofagasta",
  "Temuco",
  "Rancagua",
  "Talca",
  "Arica",
  "Chillán",

  // ヨーロッパ
  "London",
  "Birmingham",
  "Manchester",
  "Glasgow",
  "Liverpool",
  "Bristol",
  "Sheffield",
  "Leeds",
  "Edinburgh",
  "Leicester",
  "Berlin",
  "Hamburg",
  "Munich",
  "Cologne",
  "Frankfurt",
  "Stuttgart",
  "Düsseldorf",
  "Leipzig",
  "Dortmund",
  "Essen",
  "Paris",
  "Marseille",
  "Lyon",
  "Toulouse",
  "Nice",
  "Nantes",
  "Strasbourg",
  "Montpellier",
  "Bordeaux",
  "Lille",
  "Rome",
  "Milan",
  "Naples",
  "Turin",
  "Palermo",
  "Genoa",
  "Bologna",
  "Florence",
  "Bari",
  "Catania",
  "Madrid",
  "Barcelona",
  "Valencia",
  "Seville",
  "Zaragoza",
  "Málaga",
  "Murcia",
  "Palma",
  "Las Palmas",
  "Bilbao",
  "Moscow",
  "Saint Petersburg",
  "Novosibirsk",
  "Yekaterinburg",
  "Nizhny Novgorod",
  "Kazan",
  "Chelyabinsk",
  "Omsk",
  "Samara",
  "Rostov-on-Don",

  // アジア
  "Tokyo",
  "Yokohama",
  "Osaka",
  "Nagoya",
  "Sapporo",
  "Fukuoka",
  "Kobe",
  "Kyoto",
  "Kawasaki",
  "Saitama",
  "Beijing",
  "Shanghai",
  "Guangzhou",
  "Shenzhen",
  "Chongqing",
  "Tianjin",
  "Wuhan",
  "Chengdu",
  "Nanjing",
  "Xi'an",
  "Seoul",
  "Busan",
  "Incheon",
  "Daegu",
  "Daejeon",
  "Gwangju",
  "Suwon",
  "Ulsan",
  "Seongnam",
  "Goyang",
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Ahmedabad",
  "Pune",
  "Surat",
  "Jaipur",

  // オセアニア
  "Sydney",
  "Melbourne",
  "Brisbane",
  "Perth",
  "Adelaide",
  "Gold Coast",
  "Canberra",
  "Newcastle",
  "Wollongong",
  "Hobart",
  "Auckland",
  "Wellington",
  "Christchurch",
  "Hamilton",
  "Tauranga",
  "Napier-Hastings",
  "Dunedin",
  "Palmerston North",
  "Nelson",
  "Rotorua",

  // アフリカ
  "Johannesburg",
  "Cape Town",
  "Durban",
  "Pretoria",
  "Port Elizabeth",
  "Bloemfontein",
  "Nelspruit",
  "Kimberley",
  "Polokwane",
  "Pietermaritzburg",
  "Cairo",
  "Alexandria",
  "Giza",
  "Shubra El-Kheima",
  "Port Said",
  "Suez",
  "Luxor",
  "Aswan",
  "Tanta",
  "Asyut",
]

// 無線機のリスト
export const rigs = [
  "Yaesu FT-DX10",
  "Yaesu FT-991A",
  "Yaesu FT-450D",
  "Yaesu FT-891",
  "Yaesu FT-817ND",
  "Icom IC-7851",
  "Icom IC-7610",
  "Icom IC-7300",
  "Icom IC-718",
  "Icom IC-705",
  "Kenwood TS-990S",
  "Kenwood TS-890S",
  "Kenwood TS-590SG",
  "Kenwood TS-480",
  "Kenwood TS-2000",
  "Elecraft K3S",
  "Elecraft KX3",
  "Elecraft KX2",
  "Elecraft K4",
  "FlexRadio FLEX-6700",
  "FlexRadio FLEX-6600",
  "FlexRadio FLEX-6400",
  "Alinco DX-SR8T",
  "Alinco DX-SR9T",
  "Ten-Tec Orion II",
  "Ten-Tec Eagle",
  "Ten-Tec Argonaut VI",
  "QRP Labs QCX",
  "QRP Labs QSX",
  "MFJ-9200",
  "MFJ-9232",
]

// アンテナのリスト
export const antennas = [
  "Dipole",
  "Inverted V",
  "Vertical",
  "Yagi",
  "Quad",
  "Delta Loop",
  "G5RV",
  "End-Fed",
  "Magnetic Loop",
  "Hex Beam",
  "OCFD",
  "Cobweb",
  "Moxon",
  "Sloper",
  "Rhombic",
  "Beverage",
  "Discone",
  "Log Periodic",
  "Cushcraft A3S",
  "Cushcraft R8",
  "Cushcraft A4S",
  "Mosley TA-33",
  "Mosley PRO-67",
  "Mosley Classic 33",
  "HyGain TH-11DX",
  "HyGain TH-7DX",
  "HyGain TH-3MK4",
  "SteppIR DB18E",
  "SteppIR BigIR",
  "SteppIR SmallIR",
  "Diamond X510",
  "Diamond X300",
  "Diamond X200",
  "Comet GP-15",
  "Comet GP-9",
  "Comet GP-6",
  "Butternut HF9V",
  "Butternut HF6V",
  "Butternut HF5B",
  "Force 12 C3",
  "Force 12 C4XL",
  "Force 12 Sigma 5",
]

// 天気のリスト
export const weather = [
  "Sunny",
  "Clear",
  "Partly Cloudy",
  "Cloudy",
  "Overcast",
  "Rainy",
  "Drizzle",
  "Thunderstorm",
  "Snowy",
  "Foggy",
  "Windy",
  "Hot",
  "Warm",
  "Cool",
  "Cold",
  "Freezing",
  "Humid",
  "Dry",
]

// ランダムなコールサインを生成する関数
export function generateRandomCallsign(): { callsign: string; country: string; region: string } {
  // ランダムな国を選択
  const countries = Object.keys(countryPrefixes)
  const randomCountry = countries[Math.floor(Math.random() * countries.length)]
  const countryData = countryPrefixes[randomCountry]

  // ランダムなプレフィックスを選択
  const prefix = countryData.prefix[Math.floor(Math.random() * countryData.prefix.length)]

  // ランダムな数字を生成
  const number = Math.floor(Math.random() * 10)

  // ランダムなサフィックスを生成（1〜3文字）
  const suffixLength = Math.floor(Math.random() * 3) + 1
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  let suffix = ""
  for (let i = 0; i < suffixLength; i++) {
    suffix += alphabet[Math.floor(Math.random() * alphabet.length)]
  }

  return {
    callsign: `${prefix}${number}${suffix}`,
    country: countryData.country,
    region: countryData.region,
  }
}

// ランダムな局情報を生成する関数
export function generateRandomStationInfo() {
  const { callsign, country, region } = generateRandomCallsign()
  const name = operatorNames[Math.floor(Math.random() * operatorNames.length)]
  const qth = cities[Math.floor(Math.random() * cities.length)]
  const rig = rigs[Math.floor(Math.random() * rigs.length)]
  const antenna = antennas[Math.floor(Math.random() * antennas.length)]
  const wx = weather[Math.floor(Math.random() * weather.length)]

  // RSTレポートを生成（通常は5NN）
  const rst =
    Math.random() < 0.7 ? "599" : `${Math.floor(Math.random() * 4) + 2}${Math.floor(Math.random() * 4) + 6}${9}`

  return {
    callsign,
    country,
    region,
    name,
    qth,
    rig,
    antenna,
    weather: wx,
    rst,
  }
}

// コールサインが有効かチェックする関数
export function isValidCallsign(callsign: string): boolean {
  // 基本的な形式チェック: プレフィックス + 数字 + サフィックス
  const regex = /^[A-Z0-9]{1,2}[0-9][A-Z]{1,3}$/
  return regex.test(callsign)
}

